import { test, expect } from '@playwright/test'
test('catálogo REST combina filtros e mantém URL após refresh e histórico', async ({ page }) => {
  await page.goto('/?collection=Arte%20digital&network=Polygon&max=1.5&sort=lowest&page=2#catalogo')
  const catalog = page.getByRole('region', { name: 'Catálogo de NFTs' })
  await expect(catalog.locator('article').first()).toBeVisible()
  const response = await page.evaluate(async () => (await fetch(`/api/nfts${location.search}&limit=4`)).json())
  expect(response.items.every((item: { network: string; price: string }) => item.network === 'Polygon' && Number(item.price) <= 1.5 && typeof item.price === 'string')).toBe(true)
  await page.reload()
  await expect(catalog.locator('article').first()).toBeVisible()
  const pages = catalog.getByRole('navigation', { name: 'Paginação do catálogo' })
  await pages.getByRole('button', { name: 'Página 1', exact: true }).click()
  await expect(page).toHaveURL(/page=1/)
  await page.goBack()
  await expect(page).toHaveURL(/page=2/)
  await page.goForward()
  await expect(page).toHaveURL(/page=1/)
  if (page.viewportSize()!.width < 1280) await page.getByRole('button', { name: page.viewportSize()!.width < 768 ? 'Abrir filtros' : 'Filtros', exact: true }).click()
  const filters = page.viewportSize()!.width < 1280 ? page.getByRole('dialog') : catalog.locator('aside')
  await filters.getByRole('button', { name: /^Música/ }).click()
  await expect(page).toHaveURL(/collection=M%C3%BAsica/)
  await expect(page).toHaveURL(/page=1/)
  if (page.viewportSize()!.width < 1280) await page.keyboard.press('Escape')
  await page.getByRole('button', { name: /Pesquisar NFTs$/ }).click()
  await page.getByRole('dialog').getByLabel('Nome do NFT').fill('Não existe')
  await page.getByRole('dialog').getByRole('button', { name: 'Pesquisar', exact: true }).click()
  await expect(catalog).toContainText('Nenhum NFT encontrado')
  await expect(page).toHaveURL(/q=N%C3%A3o/)
  await catalog.getByRole('button', { name: 'Limpar filtros' }).click()
  await expect(catalog.locator('article').first()).toBeVisible()
  await catalog.locator('article').first().getByRole('button', { name: /^Ver detalhes/ }).click()
  await expect(page.getByRole('heading', { name: 'Emerald Ape #042' })).toBeVisible()
  await page.goto('/nft/nao-existe')
  await expect(page.getByRole('heading', { name: 'NFT não encontrado' })).toBeVisible()
})
test('latência, respostas fora de ordem e falha REST têm recuperação', async ({ page }) => {
  await page.addInitScript(() => localStorage.setItem('kurio-mock-scenario', 'slow'))
  await page.goto('/?q=Emerald#catalogo')
  await expect(page.getByRole('status', { name: 'Carregando catálogo' })).toBeVisible()
  await expect(page.getByRole('region', { name: 'Catálogo de NFTs' }).locator('article').first()).toBeVisible()
  await page.evaluate(() => fetch('/api/mock/scenario', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ scenario: 'out-of-order' }) }))
  await page.getByRole('button', { name: /Pesquisar NFTs$/ }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByLabel('Nome do NFT').fill('Ape')
  await dialog.getByRole('button', { name: 'Pesquisar', exact: true }).click()
  await page.getByRole('button', { name: /Pesquisar NFTs$/ }).click()
  await dialog.getByLabel('Nome do NFT').fill('Violet')
  await dialog.getByRole('button', { name: 'Pesquisar', exact: true }).click()
  const catalog = page.getByRole('region', { name: 'Catálogo de NFTs' })
  await expect(catalog.locator('article').first()).toContainText('Violet')
  await page.evaluate(() => fetch('/api/mock/scenario', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ scenario: 'server-error' }) }))
  await catalog.getByRole('button', { name: 'Limpar filtros' }).click()
  await expect(catalog.getByRole('alert')).toContainText('Não foi possível carregar os NFTs')
  await page.evaluate(() => fetch('/api/mock/scenario', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ scenario: 'default' }) }))
  await catalog.getByRole('button', { name: 'Tentar novamente' }).click()
  await expect(catalog.locator('article').first()).toBeVisible()
})
