import { test, expect } from '@playwright/test'
test('cadastro e edição de carteiras no perfil compartilham dados com pagamento', async ({ page }) => {
  await page.goto('/profile')
  const login = page.getByRole('dialog')
  await login.getByLabel('E-mail', { exact: true }).fill('gabriel@kurio.test')
  await login.getByLabel('Senha', { exact: true }).fill('Kurio123!')
  await login.getByRole('button', { name: 'Entrar', exact: true }).last().click()
  await page.getByRole('button', { name: 'Carteiras', exact: true }).click()
  const primary = page.getByRole('form', { name: 'Carteira principal', exact: true })
  await primary.getByLabel('Apelido da carteira', { exact: true }).fill('Principal')
  await primary.getByLabel('Rede', { exact: true }).selectOption('Ethereum')
  await primary.getByLabel('Tipo de carteira', { exact: true }).selectOption('MetaMask')
  await primary.getByLabel('Endereço da carteira', { exact: true }).fill('inválido')
  await primary.getByRole('button', { name: 'Salvar carteira' }).click()
  await expect(primary.getByRole('alert')).toContainText('Endereço da carteira inválido')
  await primary.getByLabel('Endereço da carteira', { exact: true }).fill(`0x${'a'.repeat(40)}`)
  await primary.getByLabel('Nome ENS', { exact: true }).fill('principal.kurio.eth')
  await primary.getByRole('button', { name: 'Salvar carteira' }).click()
  await expect(page.getByRole('radio', { name: 'Igual à carteira principal' })).toBeChecked()
  await page.getByRole('button', { name: 'Adicionar', exact: true }).last().click()
  const secondary = page.getByRole('form', { name: 'Carteira secundária', exact: true })
  await secondary.getByLabel('Apelido da carteira', { exact: true }).fill('Reserva')
  await secondary.getByLabel('Rede', { exact: true }).selectOption('Polygon')
  await secondary.getByLabel('Tipo de carteira', { exact: true }).selectOption('Coinbase Wallet')
  await secondary.getByLabel('Endereço da carteira', { exact: true }).fill(`0x${'b'.repeat(40)}`)
  await secondary.getByRole('button', { name: 'Salvar carteira' }).click()
  await expect(page.getByRole('radio', { name: 'Selecionar Reserva' })).toBeChecked()
  await page.getByRole('button', { name: 'Editar Reserva' }).click()
  await secondary.getByLabel('Nome ENS', { exact: true }).fill('reserva.kurio.eth')
  await secondary.getByRole('button', { name: 'Salvar carteira' }).click()
  await expect(page.getByRole('form', { name: 'Carteira secundária', exact: true })).toHaveCount(0)
  await page.reload()
  await page.getByRole('button', { name: 'Carteiras', exact: true }).click()
  await expect(primary.getByLabel('Apelido da carteira', { exact: true })).toHaveValue('Principal')
  await expect(page.getByText('reserva.kurio.eth · Polygon', { exact: true })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: `test-results/profile-wallets-${page.viewportSize()!.width}.png`, fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/checkout')
  await expect(page.getByRole('radio', { name: 'Selecionar Reserva' })).toBeChecked()
  await expect(page.getByRole('radio', { name: 'Selecionar Principal' })).toBeVisible()
})
