import { test, expect } from '@playwright/test'

test('Socket.IO atualiza preço e estoque, ignora versões antigas e reconcilia após reconectar', async ({ page }) => {
  await page.goto('/nft/emerald')
  await expect(page.locator('[data-realtime-state]')).toHaveAttribute('data-realtime-state', 'connected')
  await page.getByRole('button', { name: /^(COMPRAR|Comprar NFT)$/ }).click()
  await expect(page.locator('aside[role=status]')).toContainText('NFT adicionado')
  const update = async (body: Record<string, unknown>) => page.evaluate(async body => {
    const response = await fetch('/api/mock/realtime', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) })
    return response.status
  }, body)
  expect(await update({ action: 'nft', nftId: 'emerald', price: '2.19', edition: '1/50', available: 0, version: 2 })).toBe(200)
  await expect(page.getByRole('alert')).toContainText('Preço ou disponibilidade')
  await expect(page.getByText('2.19 ETH', { exact: true }).first()).toBeVisible()
  await expect(page.getByRole('button', { name: /^(COMPRAR|Comprar NFT)$/ })).toBeDisabled()
  await page.getByRole('button', { name: 'Revisei os novos valores' }).click()
  await update({ action: 'nft', nftId: 'emerald', price: '1.19', version: 1 })
  await update({ action: 'nft', nftId: 'emerald', price: '1.19', version: 2 })
  await expect(page.getByText('2.19 ETH', { exact: true }).first()).toBeVisible()
  await expect(page.getByRole('alert')).toHaveCount(0)
  await update({ action: 'disconnect' })
  await update({ action: 'nft', nftId: 'emerald', price: '3.19', edition: '1/50', available: 5, version: 3 })
  await expect(page.locator('[data-realtime-state]')).toHaveAttribute('data-realtime-state', 'connected')
  await expect(page.getByText('3.19 ETH', { exact: true }).first()).toBeVisible()
  await expect(page.getByRole('button', { name: /^(COMPRAR|Comprar NFT)$/ })).toBeEnabled()
})

test('pedido pendente sobrevive ao refresh e recebe confirmação ou recusa pelo socket', async ({ page }) => {
  await page.goto('/checkout')
  const login = page.getByRole('dialog')
  await login.getByLabel('E-mail', { exact: true }).fill('gabriel@kurio.test')
  await login.getByLabel('Senha', { exact: true }).fill('Kurio123!')
  await login.getByRole('button', { name: 'Entrar', exact: true }).last().click()
  await expect(login).toHaveCount(0)
  await expect.poll(() => page.evaluate(() => localStorage.getItem('kurio-session-token'))).toBeTruthy()
  await expect(page.locator('[data-realtime-state]')).toHaveAttribute('data-realtime-state', 'connected')
  const create = async () => page.evaluate(async () => {
    const headers = { Authorization: `Bearer ${localStorage.getItem('kurio-session-token')}`, 'Content-Type': 'application/json' }
    const request = async (path: string, body: unknown) => (await fetch(`/api/${path}`, { method: 'POST', headers, body: JSON.stringify(body) })).json()
    let wallets = await (await fetch('/api/wallets', { headers })).json()
    if (!wallets.items.length) wallets = await request('wallets', { name: 'Principal', type: 'MetaMask', network: 'Ethereum', address: `0x${'a'.repeat(40)}` })
    await request('cart', { nftId: 'emerald', edition: '1/50', quantity: 1 })
    const cart = await (await fetch('/api/cart', { headers })).json()
    await fetch('/api/mock/scenario', { method: 'PUT', headers, body: JSON.stringify({ scenario: 'pending-order' }) })
    return (await fetch('/api/orders', { method: 'POST', headers: { ...headers, 'Idempotency-Key': crypto.randomUUID() }, body: JSON.stringify({ walletId: wallets.items[0].id, expectedTotal: cart.total, expectedRevision: cart.revision }) })).json()
  })
  const order = await create()
  await page.goto(`/checkout?order=${order.id}`)
  await expect(page.getByRole('heading', { name: 'Compra em processamento' })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Compra em processamento' })).toBeVisible()
  await expect(page.locator('[data-realtime-state]')).toHaveAttribute('data-realtime-state', 'connected')
  await page.evaluate(async id => {
    const post = (body: unknown) => fetch('/api/mock/realtime', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) })
    await post({ action: 'disconnect' })
    await post({ action: 'order', orderId: id, status: 'confirmed' })
  }, order.id)
  await expect(page.getByRole('heading', { name: 'Seus NFTs agora estão na sua carteira' })).toBeVisible()
  const second = await create()
  await page.goto(`/checkout?order=${second.id}`)
  await expect(page.getByRole('heading', { name: 'Compra em processamento' })).toBeVisible()
  await expect(page.locator('[data-realtime-state]')).toHaveAttribute('data-realtime-state', 'connected')
  await page.evaluate(id => fetch('/api/mock/realtime', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action: 'order', orderId: id, status: 'refused' }) }), second.id)
  await expect(page.getByRole('heading', { name: 'Pagamento recusado' })).toBeVisible()
  const state = await page.evaluate(() => {
    const db = JSON.parse(localStorage.getItem('kurio-mock-database-v1')!)
    return { orders: db.orders.length, quantities: Object.values(db.carts).flatMap((cart: { items: { quantity: number }[] }) => cart.items).map((item: { quantity: number }) => item.quantity) }
  })
  expect(state.orders).toBe(2)
  expect(state.quantities).toContain(1)
})
